name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore Karaoke.sln
      - name: Build
        run: dotnet build Karaoke.sln -c Release --no-restore
      - name: Test
        run: dotnet test Karaoke.sln -c Release --no-build --collect:"XPlat Code Coverage"
      - name: Verify formatting
        run: dotnet format Karaoke.sln --verify-no-changes
